lib: [
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/META"
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/BriskTyxmlBinPesyModules.a" {"bin/pesy-modules/BriskTyxmlBinPesyModules.a"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/BriskTyxmlBinPesyModules.cma" {"bin/pesy-modules/BriskTyxmlBinPesyModules.cma"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/BriskTyxmlBinPesyModules.cmxa" {"bin/pesy-modules/BriskTyxmlBinPesyModules.cmxa"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/BriskTyxmlBinPesyModules.cmxs" {"bin/pesy-modules/BriskTyxmlBinPesyModules.cmxs"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/BriskTyxmlBinPesyModules.re" {"bin/pesy-modules/BriskTyxmlBinPesyModules.re"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/briskTyxmlBinPesyModules.cmi" {"bin/pesy-modules/briskTyxmlBinPesyModules.cmi"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/briskTyxmlBinPesyModules.cmt" {"bin/pesy-modules/briskTyxmlBinPesyModules.cmt"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/bin/pesy-modules/briskTyxmlBinPesyModules.cmx" {"bin/pesy-modules/briskTyxmlBinPesyModules.cmx"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/dune-package"
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/BriskTyxmlLibrary.a" {"library/BriskTyxmlLibrary.a"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/BriskTyxmlLibrary.cma" {"library/BriskTyxmlLibrary.cma"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/BriskTyxmlLibrary.cmxa" {"library/BriskTyxmlLibrary.cmxa"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/BriskTyxmlLibrary.cmxs" {"library/BriskTyxmlLibrary.cmxs"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/BriskXml.ml" {"library/BriskXml.ml"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/React.ml" {"library/React.ml"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/Util.re" {"library/Util.re"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/Util.rei" {"library/Util.rei"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary.cmi" {"library/briskTyxmlLibrary.cmi"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary.cmt" {"library/briskTyxmlLibrary.cmt"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary.cmx" {"library/briskTyxmlLibrary.cmx"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary.ml" {"library/briskTyxmlLibrary.ml"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__BriskXml.cmi" {"library/briskTyxmlLibrary__BriskXml.cmi"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__BriskXml.cmt" {"library/briskTyxmlLibrary__BriskXml.cmt"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__BriskXml.cmx" {"library/briskTyxmlLibrary__BriskXml.cmx"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__React.cmi" {"library/briskTyxmlLibrary__React.cmi"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__React.cmt" {"library/briskTyxmlLibrary__React.cmt"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__React.cmx" {"library/briskTyxmlLibrary__React.cmx"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__Util.cmi" {"library/briskTyxmlLibrary__Util.cmi"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__Util.cmt" {"library/briskTyxmlLibrary__Util.cmt"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__Util.cmti" {"library/briskTyxmlLibrary__Util.cmti"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/library/briskTyxmlLibrary__Util.cmx" {"library/briskTyxmlLibrary__Util.cmx"}
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/lib/brisk-tyxml/opam"
]
bin: [
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/bin/BriskTyxmlApp.exe"
]
doc: [
  "/Users/ulrik.strid/dev/reason-native-web/brisk-tyxml/_esy/default/store/b/brisk_tyxml-bfad02f1/install/default/doc/brisk-tyxml/README.md"
]
